<?php

/**
 * PluginpkRedirectTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginpkRedirectTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginpkRedirectTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginpkRedirect');
    }
}